export const LOGINPOPUP_ACTION_TYPES = {
    SET_POPUP_OPEN: 'SET_POPUP_OPEN',
    SET_SIGNUP_OPEN: 'SET_SIGNUP_OPEN',
    SET_SIGNIN_OPEN: 'SET_SIGNIN_OPEN',
    SET_EMAIL_SIGNUP_OPEN: 'SET_EMAIL_SIGNUP_OPEN',
    SET_EMAIL_SIGNIN_OPEN: 'SET_EMAIL_SIGNIN_OPEN',
    CLOSE_POPUP: 'CLOSE_POPUP',
}
